### ISSUE TITLE
Elastic Beanstalk survey launcher not loading list of surveys

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/eq-terraform#148]
### Expected behaviour
The survey list in the Elastic Beanstalk survey launcher should be populated with the list of surveys from the associated survey runner.

### Actual behaviour
The survey list is not populated. This is due to the Elastic Beanstalk survey launcher not being able to access survey runner to get the list of surveys. 

### Steps to reproduce the behaviour
- Run Terraform
- Deploy survey runner to Elastic Beanstalk
- Try and select a survey in the survey launcher

**Comment by jonnyshaw89** [comment]
This works
