### ISSUE TITLE
Application references admin and readonly RabbitMQ users

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/eq-terraform#78]
### Expected behaviour
The `survey-runner-application` Terraform only uses the `write` user when setting up the application, so we should be able to run it without setting the `read` and `admin` users.

### Actual behaviour
The `read` and `admin` users and passwords need to be specified to run the `survey-runner-application` Terraform

### Steps to reproduce the behaviour
Run the `survey-runner-application` Terraform without setting the `read` or `admin` user details

**Comment by jonnyshaw89** [comment]
The `admin` and `read` user details are no longer passed to `survey-runner-application`
